font_family       BerkeleyMono Nerd Font Mono Plus Font Awesome Plus Font Awesome Extension Plus Octicons Plus Power Symbols Plus Codicons Plus Pomicons Plus Font Logos Plus Material Design Icons Plus Weather Icons
bold_font         auto
italic_font       auto
bold_italic_font  auto
font_size         16.0
disable_ligatures always

macos_option_as_alt yes

# Theme is handled by dark-theme.auto.conf and light-theme.auto.conf
