-- Render LSP inlay hints at the end of the line instead of inline.
-- (Inlay hints are enabled per-buffer on LspAttach; see config/lsp.lua.)
-- Disabled: prefer Helix-like inline rendering from native vim.lsp.inlay_hint.
-- require("lsp-endhints").setup()
